import { StyleSheet, ViewStyle, TextStyle } from 'react-native';

export type Language = 'en' | 'de' | 'es' | 'fr';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Onboarding
    'onboarding.welcome': 'Welcome to PulsLog',
    'onboarding.welcome.description': 'Track your health metrics and stay informed about your circulatory health.',
    'onboarding.name': "What's your name?",
    'onboarding.age': 'Your Age',
    'onboarding.age.description': 'This helps us calculate your baseline health metrics.',
    'onboarding.gender': 'Your Gender',
    'onboarding.gender.description': 'This helps us provide personalized health insights.',
    'onboarding.measurements': 'Your Measurements',
    'onboarding.measurements.description': 'Height (cm) and Weight (kg) help us calculate your health baseline.',
    'onboarding.language': 'Select Your Language',
    'onboarding.language.description': 'Choose your preferred language for the app.',
    'onboarding.next': 'Next',
    'onboarding.back': 'Back',
    'onboarding.getStarted': 'Get Started',
    'onboarding.enterName': 'Enter your name',
    'onboarding.enterAge': 'Enter your age',
    'onboarding.height': 'Height (cm)',
    'onboarding.weight': 'Weight (kg)',
    'onboarding.male': 'Male',
    'onboarding.female': 'Female',
    'onboarding.other': 'Other',

    // Profile
    'profile.title': 'Profile',
    'profile.healthProfile': 'Health Profile',
    'profile.height': 'Height',
    'profile.weight': 'Weight',
    'profile.avgPulse': 'Avg. Pulse',
    'profile.averagePulseByActivity': 'Average Pulse by Activity Level',
    'profile.resting': 'Resting',
    'profile.lightActivity': 'Light Activity',
    'profile.sportsActivity': 'Sports Activity',
    'profile.healthBaselines': 'Health Baselines',
    'profile.systolic': 'Systolic',
    'profile.diastolic': 'Diastolic',
    'profile.about': 'About PulsLog',
    'profile.aboutDescription': 'PulsLog helps you track your pulse, blood pressure, and medication data. It\'s designed for people with POTS and other circulatory disorders.',
    'profile.version': 'Version 1.0.0',
    'profile.resetProfile': 'Reset Profile',
    'profile.language': 'Language',
    'profile.editProfile': 'Edit Profile',
    'profile.cancel': 'Cancel',
    'profile.save': 'Save',
    'profile.resetConfirm': 'Reset Profile',
    'profile.resetConfirmMessage': 'Are you sure you want to reset your profile? This will take you back to the onboarding screen.',

    // Other/Organizer
    'other.title': 'Organizer',
    'other.description': 'Manage your tasks, shopping, and notes',
    'other.todos': '✓ To-Do Lists',
    'other.shopping': '🛒 Shopping Lists',
    'other.notes': '📝 Notes',
    'other.dataLocal': 'All your data is saved locally on your device',

    // Common
    'common.list': 'list',
    'common.lists': 'lists',
    'common.note': 'note',
    'common.notes': 'notes',
    
    // Add Entry
    'addEntry.title': 'Add Health Entry',
    'addEntry.time': 'Time',
    'addEntry.activityLevel': 'Activity Level',
    'addEntry.resting': 'Resting',
    'addEntry.light': 'Light Activity',
    'addEntry.sports': 'Sports Activity',
    'addEntry.medication': 'Medication',
    'addEntry.medicationName': 'Medication name',
    'addEntry.medicationAmount': 'Amount (e.g., 1 tablet, 5ml)',
    'addEntry.pulse': 'Pulse (bpm)',
    'addEntry.pulseResting': 'Resting',
    'addEntry.pulseSitting': 'Sitting',
    'addEntry.pulseStanding': 'Standing',
    'addEntry.bloodPressure': 'Blood Pressure (mmHg)',
    'addEntry.systolic': 'Systolic',
    'addEntry.diastolic': 'Diastolic',
    'addEntry.mood': 'Mood / Well-being',
    'addEntry.notes': 'Notes',
    'addEntry.additionalNotes': 'Any additional notes',
    'addEntry.cancel': 'Cancel',
    'addEntry.save': 'Save Entry',
    'addEntry.error': 'Please enter at least pulse or blood pressure data',
    'addEntry.success': 'Entry saved successfully',
    
    // Calendar
    'calendar.title': 'Calendar',
    'calendar.deleteEntry': 'Delete Entry',
    'calendar.deleteConfirm': 'Are you sure you want to delete this entry?',
    'calendar.noEntries': 'No entries for',
    'calendar.pulse': 'Pulse',
    'calendar.bp': 'BP',
    'calendar.medication': 'Medication',
    
    // Reminders
    'reminders.title': 'Reminders',
    'reminders.description': 'Set reminders for your measurements and medications',
    'reminders.pulse': 'Pulse Measurements',
    'reminders.medicationReminder': 'Medication',
    'reminders.addPulse': 'Add Pulse Reminder',
    'reminders.addMedication': 'Add Medication Reminder',
    'reminders.note': 'Note',
    'reminders.noteText': 'Reminders are stored locally on your device. Enable notifications in your device settings to receive alerts.',
    
    // Forum
    'forum.title': 'Community Forum',
    'forum.placeholder': 'Share your thoughts or ask a question...',
    'forum.post': 'Post',
    'forum.recentMessages': 'Recent Messages',
    'forum.noMessages': 'No messages yet. Be the first to post!',
    'forum.error': 'Please enter a message',
    'forum.success': 'Message posted!',
    
    // Todos
    'todos.title': 'To-Do Lists',
    'todos.newList': 'New List',
    'todos.noLists': 'No To-Do Lists Yet',
    'todos.createFirst': 'Create your first list to get started',
    'todos.noTasks': 'No Tasks Yet',
    'todos.addTask': 'Add a task to get started',
    'todos.newTask': 'New Task',
    'todos.taskTitle': 'Task Title',
    'todos.enterTaskTitle': 'Enter task title',
    'todos.dueDate': 'Due Date (Optional)',
    'todos.selectDate': 'Select date',
    'todos.dueTime': 'Due Time (Optional)',
    'todos.selectTime': 'Select time',
    'todos.listName': 'List Name',
    'todos.enterListName': 'Enter list name',
    'todos.deleteList': 'Delete List',
    'todos.deleteListConfirm': 'Are you sure you want to delete this list?',
    'todos.deleteTask': 'Delete Task',
    'todos.deleteTaskConfirm': 'Are you sure you want to delete this task?',
    'todos.task': 'task',
    'todos.tasks': 'tasks',
    'todos.create': 'Create',
    'todos.addTaskBtn': 'Add Task',
    'todos.error': 'Please enter a task title',
    'todos.errorList': 'Please enter a list name',
    
    // Shopping
    'shopping.title': 'Shopping Lists',
    'shopping.newList': 'New List',
    'shopping.noLists': 'No Shopping Lists Yet',
    'shopping.createFirst': 'Create your first list to get started',
    'shopping.noItems': 'No Items Yet',
    'shopping.addItem': 'Add an item to get started',
    'shopping.newItem': 'New Item',
    'shopping.itemName': 'Item Name',
    'shopping.enterItemName': 'Enter item name',
    'shopping.quantity': 'Quantity (Optional)',
    'shopping.quantityPlaceholder': 'e.g., 2 kg, 1 dozen',
    'shopping.category': 'Category',
    'shopping.listName': 'List Name',
    'shopping.enterListName': 'Enter list name',
    'shopping.deleteList': 'Delete List',
    'shopping.deleteListConfirm': 'Are you sure you want to delete this list?',
    'shopping.deleteItem': 'Delete Item',
    'shopping.deleteItemConfirm': 'Are you sure you want to delete this item?',
    'shopping.items': 'items',
    'shopping.qty': 'Qty',
    'shopping.create': 'Create',
    'shopping.addItem': 'Add Item',
    'shopping.error': 'Please enter an item name',
    'shopping.errorList': 'Please enter a list name',
    
    // Notes
    'notes.title': 'Notes',
    'notes.newNote': 'New Note',
    'notes.noNotes': 'No Notes Yet',
    'notes.createFirst': 'Create your first note to get started',
    'notes.noteTitle': 'Title',
    'notes.enterTitle': 'Enter note title',
    'notes.content': 'Content',
    'notes.enterContent': 'Enter note content',
    'notes.date': 'Date (Optional)',
    'notes.selectDate': 'Select date',
    'notes.time': 'Time (Optional)',
    'notes.selectTime': 'Select time',
    'notes.deleteNote': 'Delete Note',
    'notes.deleteConfirm': 'Are you sure you want to delete this note?',
    'notes.editNote': 'Edit Note',
    'notes.update': 'Update',
    'notes.error': 'Please enter a title and content',
    
    // Home
    'home.welcome': 'Welcome',
    'home.trackHealth': 'Track your health metrics and stay informed',
    'home.calendar': 'Calendar',
    'home.calendarDesc': 'View your health records by date',
    'home.addEntry': 'Add Entry',
    'home.addEntryDesc': 'Record pulse, blood pressure & medication',
    'home.samsungHealth': 'Samsung Health',
    'home.samsungHealthDesc': 'Sync data from your Galaxy Watch 7',
    'home.healthInfo': 'Health Info',
    'home.healthInfoDesc': 'Learn about POTS and circulatory disorders',
    'home.reminders': 'Reminders',
    'home.remindersDesc': 'Set reminders for measurements & medication',
    'home.forum': 'Forum',
    'home.forumDesc': 'Connect with community members',
    'home.lastUpdated': 'Last updated',
  },
  de: {
    // Onboarding
    'onboarding.welcome': 'Willkommen bei PulsLog',
    'onboarding.welcome.description': 'Verfolgen Sie Ihre Gesundheitsmetriken und bleiben Sie über Ihre Kreislaufgesundheit informiert.',
    'onboarding.name': 'Wie heißen Sie?',
    'onboarding.age': 'Ihr Alter',
    'onboarding.age.description': 'Dies hilft uns, Ihre Basis-Gesundheitsmetriken zu berechnen.',
    'onboarding.gender': 'Ihr Geschlecht',
    'onboarding.gender.description': 'Dies hilft uns, personalisierte Gesundheitseinblicke zu geben.',
    'onboarding.measurements': 'Ihre Messungen',
    'onboarding.measurements.description': 'Größe (cm) und Gewicht (kg) helfen uns, Ihre Gesundheitsgrundlage zu berechnen.',
    'onboarding.language': 'Wählen Sie Ihre Sprache',
    'onboarding.language.description': 'Wählen Sie Ihre bevorzugte Sprache für die App.',
    'onboarding.next': 'Weiter',
    'onboarding.back': 'Zurück',
    'onboarding.getStarted': 'Loslegen',
    'onboarding.enterName': 'Geben Sie Ihren Namen ein',
    'onboarding.enterAge': 'Geben Sie Ihr Alter ein',
    'onboarding.height': 'Größe (cm)',
    'onboarding.weight': 'Gewicht (kg)',
    'onboarding.male': 'Männlich',
    'onboarding.female': 'Weiblich',
    'onboarding.other': 'Sonstiges',

    // Profile
    'profile.title': 'Profil',
    'profile.healthProfile': 'Gesundheitsprofil',
    'profile.height': 'Größe',
    'profile.weight': 'Gewicht',
    'profile.avgPulse': 'Durchschn. Puls',
    'profile.averagePulseByActivity': 'Durchschnittlicher Puls nach Aktivitätsniveau',
    'profile.resting': 'Ruhe',
    'profile.lightActivity': 'Leichte Aktivität',
    'profile.sportsActivity': 'Sportliche Aktivität',
    'profile.healthBaselines': 'Gesundheitsgrundlagen',
    'profile.systolic': 'Systolisch',
    'profile.diastolic': 'Diastolisch',
    'profile.about': 'Über PulsLog',
    'profile.aboutDescription': 'PulsLog hilft Ihnen, Ihren Puls, Blutdruck und Medikamentendaten zu verfolgen. Es ist für Menschen mit POTS und anderen Kreislaufstörungen konzipiert.',
    'profile.version': 'Version 1.0.0',
    'profile.resetProfile': 'Profil zurücksetzen',
    'profile.language': 'Sprache',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.cancel': 'Abbrechen',
    'profile.save': 'Speichern',
    'profile.resetConfirm': 'Profil zurücksetzen',
    'profile.resetConfirmMessage': 'Sind Sie sicher, dass Sie Ihr Profil zurücksetzen möchten? Dies bringt Sie zurück zum Onboarding-Bildschirm.',

    // Other/Organizer
    'other.title': 'Organizer',
    'other.description': 'Verwalten Sie Ihre Aufgaben, Einkäufe und Notizen',
    'other.todos': '✓ To-Do-Listen',
    'other.shopping': '🛒 Einkaufslisten',
    'other.notes': '📝 Notizen',
    'other.dataLocal': 'Alle Ihre Daten werden lokal auf Ihrem Gerät gespeichert',

    // Common
    'common.list': 'Liste',
    'common.lists': 'Listen',
    'common.note': 'Notiz',
    'common.notes': 'Notizen',
    
    // Add Entry
    'addEntry.title': 'Gesundheitseintrag hinzufügen',
    'addEntry.time': 'Zeit',
    'addEntry.activityLevel': 'Aktivitätsniveau',
    'addEntry.resting': 'Ruhe',
    'addEntry.light': 'Leichte Aktivität',
    'addEntry.sports': 'Sportliche Aktivität',
    'addEntry.medication': 'Medikament',
    'addEntry.medicationName': 'Medikamentenname',
    'addEntry.medicationAmount': 'Menge (z.B. 1 Tablette, 5ml)',
    'addEntry.pulse': 'Puls (bpm)',
    'addEntry.pulseResting': 'Ruhe',
    'addEntry.pulseSitting': 'Sitzend',
    'addEntry.pulseStanding': 'Stehend',
    'addEntry.bloodPressure': 'Blutdruck (mmHg)',
    'addEntry.systolic': 'Systolisch',
    'addEntry.diastolic': 'Diastolisch',
    'addEntry.mood': 'Stimmung / Wohlbefinden',
    'addEntry.notes': 'Notizen',
    'addEntry.additionalNotes': 'Zusätzliche Notizen',
    'addEntry.cancel': 'Abbrechen',
    'addEntry.save': 'Eintrag speichern',
    'addEntry.error': 'Bitte geben Sie mindestens Puls- oder Blutdruckdaten ein',
    'addEntry.success': 'Eintrag erfolgreich gespeichert',
    
    // Calendar
    'calendar.title': 'Kalender',
    'calendar.deleteEntry': 'Eintrag löschen',
    'calendar.deleteConfirm': 'Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?',
    'calendar.noEntries': 'Keine Einträge für',
    'calendar.pulse': 'Puls',
    'calendar.bp': 'BD',
    'calendar.medication': 'Medikament',
    
    // Reminders
    'reminders.title': 'Erinnerungen',
    'reminders.description': 'Stellen Sie Erinnerungen für Ihre Messungen und Medikamente ein',
    'reminders.pulse': 'Pulsmessungen',
    'reminders.medicationReminder': 'Medikament',
    'reminders.addPulse': 'Pulserinnerung hinzufügen',
    'reminders.addMedication': 'Medikamentenerinnerung hinzufügen',
    'reminders.note': 'Hinweis',
    'reminders.noteText': 'Erinnerungen werden lokal auf Ihrem Gerät gespeichert. Aktivieren Sie Benachrichtigungen in Ihren Geräteeinstellungen, um Benachrichtigungen zu erhalten.',
    
    // Forum
    'forum.title': 'Community-Forum',
    'forum.placeholder': 'Teilen Sie Ihre Gedanken oder stellen Sie eine Frage...',
    'forum.post': 'Posten',
    'forum.recentMessages': 'Aktuelle Nachrichten',
    'forum.noMessages': 'Noch keine Nachrichten. Seien Sie der Erste, der postet!',
    'forum.error': 'Bitte geben Sie eine Nachricht ein',
    'forum.success': 'Nachricht gepostet!',
    
    // Todos
    'todos.title': 'To-Do-Listen',
    'todos.newList': 'Neue Liste',
    'todos.noLists': 'Noch keine To-Do-Listen',
    'todos.createFirst': 'Erstellen Sie Ihre erste Liste, um zu beginnen',
    'todos.noTasks': 'Noch keine Aufgaben',
    'todos.addTask': 'Fügen Sie eine Aufgabe hinzu, um zu beginnen',
    'todos.newTask': 'Neue Aufgabe',
    'todos.taskTitle': 'Aufgabentitel',
    'todos.enterTaskTitle': 'Geben Sie den Aufgabentitel ein',
    'todos.dueDate': 'Fälligkeitsdatum (Optional)',
    'todos.selectDate': 'Datum auswählen',
    'todos.dueTime': 'Fälligkeitszeit (Optional)',
    'todos.selectTime': 'Zeit auswählen',
    'todos.listName': 'Listenname',
    'todos.enterListName': 'Geben Sie den Listennamen ein',
    'todos.deleteList': 'Liste löschen',
    'todos.deleteListConfirm': 'Sind Sie sicher, dass Sie diese Liste löschen möchten?',
    'todos.deleteTask': 'Aufgabe löschen',
    'todos.deleteTaskConfirm': 'Sind Sie sicher, dass Sie diese Aufgabe löschen möchten?',
    'todos.task': 'Aufgabe',
    'todos.tasks': 'Aufgaben',
    'todos.create': 'Erstellen',
    'todos.addTaskBtn': 'Aufgabe hinzufügen',
    'todos.error': 'Bitte geben Sie einen Aufgabentitel ein',
    'todos.errorList': 'Bitte geben Sie einen Listennamen ein',
    
    // Shopping
    'shopping.title': 'Einkaufslisten',
    'shopping.newList': 'Neue Liste',
    'shopping.noLists': 'Noch keine Einkaufslisten',
    'shopping.createFirst': 'Erstellen Sie Ihre erste Liste, um zu beginnen',
    'shopping.noItems': 'Noch keine Artikel',
    'shopping.addItem': 'Fügen Sie einen Artikel hinzu, um zu beginnen',
    'shopping.newItem': 'Neuer Artikel',
    'shopping.itemName': 'Artikelname',
    'shopping.enterItemName': 'Geben Sie den Artikelnamen ein',
    'shopping.quantity': 'Menge (Optional)',
    'shopping.quantityPlaceholder': 'z.B. 2 kg, 1 Dutzend',
    'shopping.category': 'Kategorie',
    'shopping.listName': 'Listenname',
    'shopping.enterListName': 'Geben Sie den Listennamen ein',
    'shopping.deleteList': 'Liste löschen',
    'shopping.deleteListConfirm': 'Sind Sie sicher, dass Sie diese Liste löschen möchten?',
    'shopping.deleteItem': 'Artikel löschen',
    'shopping.deleteItemConfirm': 'Sind Sie sicher, dass Sie diesen Artikel löschen möchten?',
    'shopping.items': 'Artikel',
    'shopping.qty': 'Menge',
    'shopping.create': 'Erstellen',
    'shopping.addItem': 'Artikel hinzufügen',
    'shopping.error': 'Bitte geben Sie einen Artikelnamen ein',
    'shopping.errorList': 'Bitte geben Sie einen Listennamen ein',
    
    // Notes
    'notes.title': 'Notizen',
    'notes.newNote': 'Neue Notiz',
    'notes.noNotes': 'Noch keine Notizen',
    'notes.createFirst': 'Erstellen Sie Ihre erste Notiz, um zu beginnen',
    'notes.noteTitle': 'Titel',
    'notes.enterTitle': 'Geben Sie den Notiztitel ein',
    'notes.content': 'Inhalt',
    'notes.enterContent': 'Geben Sie den Notizinhalt ein',
    'notes.date': 'Datum (Optional)',
    'notes.selectDate': 'Datum auswählen',
    'notes.time': 'Zeit (Optional)',
    'notes.selectTime': 'Zeit auswählen',
    'notes.deleteNote': 'Notiz löschen',
    'notes.deleteConfirm': 'Sind Sie sicher, dass Sie diese Notiz löschen möchten?',
    'notes.editNote': 'Notiz bearbeiten',
    'notes.update': 'Aktualisieren',
    'notes.error': 'Bitte geben Sie einen Titel und Inhalt ein',
    
    // Home
    'home.welcome': 'Willkommen',
    'home.trackHealth': 'Verfolgen Sie Ihre Gesundheitsmetriken und bleiben Sie informiert',
    'home.calendar': 'Kalender',
    'home.calendarDesc': 'Sehen Sie Ihre Gesundheitsakten nach Datum',
    'home.addEntry': 'Eintrag hinzufügen',
    'home.addEntryDesc': 'Erfassen Sie Puls, Blutdruck und Medikamente',
    'home.samsungHealth': 'Samsung Health',
    'home.samsungHealthDesc': 'Synchronisieren Sie Daten von Ihrer Galaxy Watch 7',
    'home.healthInfo': 'Gesundheitsinformationen',
    'home.healthInfoDesc': 'Erfahren Sie mehr über POTS und Kreislaufstörungen',
    'home.reminders': 'Erinnerungen',
    'home.remindersDesc': 'Stellen Sie Erinnerungen für Messungen und Medikamente ein',
    'home.forum': 'Forum',
    'home.forumDesc': 'Verbinden Sie sich mit Community-Mitgliedern',
    'home.lastUpdated': 'Zuletzt aktualisiert',
  },
  es: {
    // Onboarding
    'onboarding.welcome': 'Bienvenido a PulsLog',
    'onboarding.welcome.description': 'Realice un seguimiento de sus métricas de salud y manténgase informado sobre su salud circulatoria.',
    'onboarding.name': '¿Cuál es su nombre?',
    'onboarding.age': 'Su Edad',
    'onboarding.age.description': 'Esto nos ayuda a calcular sus métricas de salud de referencia.',
    'onboarding.gender': 'Su Género',
    'onboarding.gender.description': 'Esto nos ayuda a proporcionar información de salud personalizada.',
    'onboarding.measurements': 'Sus Medidas',
    'onboarding.measurements.description': 'La altura (cm) y el peso (kg) nos ayudan a calcular su línea de base de salud.',
    'onboarding.language': 'Seleccione Su Idioma',
    'onboarding.language.description': 'Elija su idioma preferido para la aplicación.',
    'onboarding.next': 'Siguiente',
    'onboarding.back': 'Atrás',
    'onboarding.getStarted': 'Comenzar',
    'onboarding.enterName': 'Ingrese su nombre',
    'onboarding.enterAge': 'Ingrese su edad',
    'onboarding.height': 'Altura (cm)',
    'onboarding.weight': 'Peso (kg)',
    'onboarding.male': 'Masculino',
    'onboarding.female': 'Femenino',
    'onboarding.other': 'Otro',

    // Profile
    'profile.title': 'Perfil',
    'profile.healthProfile': 'Perfil de Salud',
    'profile.height': 'Altura',
    'profile.weight': 'Peso',
    'profile.avgPulse': 'Pulso Promedio',
    'profile.averagePulseByActivity': 'Pulso Promedio por Nivel de Actividad',
    'profile.resting': 'Reposo',
    'profile.lightActivity': 'Actividad Ligera',
    'profile.sportsActivity': 'Actividad Deportiva',
    'profile.healthBaselines': 'Líneas de Base de Salud',
    'profile.systolic': 'Sistólica',
    'profile.diastolic': 'Diastólica',
    'profile.about': 'Acerca de PulsLog',
    'profile.aboutDescription': 'PulsLog le ayuda a realizar un seguimiento de su pulso, presión arterial y datos de medicamentos. Está diseñado para personas con POTS y otros trastornos circulatorios.',
    'profile.version': 'Versión 1.0.0',
    'profile.resetProfile': 'Restablecer Perfil',
    'profile.language': 'Idioma',
    'profile.editProfile': 'Editar Perfil',
    'profile.cancel': 'Cancelar',
    'profile.save': 'Guardar',
    'profile.resetConfirm': 'Restablecer Perfil',
    'profile.resetConfirmMessage': '¿Está seguro de que desea restablecer su perfil? Esto lo llevará de vuelta a la pantalla de incorporación.',

    // Other/Organizer
    'other.title': 'Organizador',
    'other.description': 'Administre sus tareas, compras y notas',
    'other.todos': '✓ Listas de Tareas',
    'other.shopping': '🛒 Listas de Compras',
    'other.notes': '📝 Notas',
    'other.dataLocal': 'Todos sus datos se guardan localmente en su dispositivo',

    // Common
    'common.list': 'lista',
    'common.lists': 'listas',
    'common.note': 'nota',
    'common.notes': 'notas',
    
    // Add Entry
    'addEntry.title': 'Agregar Entrada de Salud',
    'addEntry.time': 'Hora',
    'addEntry.activityLevel': 'Nivel de Actividad',
    'addEntry.resting': 'Reposo',
    'addEntry.light': 'Actividad Ligera',
    'addEntry.sports': 'Actividad Deportiva',
    'addEntry.medication': 'Medicamento',
    'addEntry.medicationName': 'Nombre del medicamento',
    'addEntry.medicationAmount': 'Cantidad (p.ej., 1 tableta, 5ml)',
    'addEntry.pulse': 'Pulso (bpm)',
    'addEntry.pulseResting': 'Reposo',
    'addEntry.pulseSitting': 'Sentado',
    'addEntry.pulseStanding': 'De pie',
    'addEntry.bloodPressure': 'Presión Arterial (mmHg)',
    'addEntry.systolic': 'Sistólica',
    'addEntry.diastolic': 'Diastólica',
    'addEntry.mood': 'Estado de Ánimo / Bienestar',
    'addEntry.notes': 'Notas',
    'addEntry.additionalNotes': 'Notas adicionales',
    'addEntry.cancel': 'Cancelar',
    'addEntry.save': 'Guardar Entrada',
    'addEntry.error': 'Por favor ingrese al menos datos de pulso o presión arterial',
    'addEntry.success': 'Entrada guardada exitosamente',
    
    // Calendar
    'calendar.title': 'Calendario',
    'calendar.deleteEntry': 'Eliminar Entrada',
    'calendar.deleteConfirm': '¿Está seguro de que desea eliminar esta entrada?',
    'calendar.noEntries': 'Sin entradas para',
    'calendar.pulse': 'Pulso',
    'calendar.bp': 'PA',
    'calendar.medication': 'Medicamento',
    
    // Reminders
    'reminders.title': 'Recordatorios',
    'reminders.description': 'Establezca recordatorios para sus mediciones y medicamentos',
    'reminders.pulse': 'Mediciones de Pulso',
    'reminders.medicationReminder': 'Medicamento',
    'reminders.addPulse': 'Agregar Recordatorio de Pulso',
    'reminders.addMedication': 'Agregar Recordatorio de Medicamento',
    'reminders.note': 'Nota',
    'reminders.noteText': 'Los recordatorios se guardan localmente en su dispositivo. Habilite las notificaciones en la configuración de su dispositivo para recibir alertas.',
    
    // Forum
    'forum.title': 'Foro Comunitario',
    'forum.placeholder': 'Comparta sus pensamientos o haga una pregunta...',
    'forum.post': 'Publicar',
    'forum.recentMessages': 'Mensajes Recientes',
    'forum.noMessages': '¡Sin mensajes aún. Sé el primero en publicar!',
    'forum.error': 'Por favor ingrese un mensaje',
    'forum.success': '¡Mensaje publicado!',
    
    // Todos
    'todos.title': 'Listas de Tareas',
    'todos.newList': 'Nueva Lista',
    'todos.noLists': 'Sin Listas de Tareas Aún',
    'todos.createFirst': 'Cree su primera lista para comenzar',
    'todos.noTasks': 'Sin Tareas Aún',
    'todos.addTask': 'Agregue una tarea para comenzar',
    'todos.newTask': 'Nueva Tarea',
    'todos.taskTitle': 'Título de la Tarea',
    'todos.enterTaskTitle': 'Ingrese el título de la tarea',
    'todos.dueDate': 'Fecha de Vencimiento (Opcional)',
    'todos.selectDate': 'Seleccionar fecha',
    'todos.dueTime': 'Hora de Vencimiento (Opcional)',
    'todos.selectTime': 'Seleccionar hora',
    'todos.listName': 'Nombre de la Lista',
    'todos.enterListName': 'Ingrese el nombre de la lista',
    'todos.deleteList': 'Eliminar Lista',
    'todos.deleteListConfirm': '¿Está seguro de que desea eliminar esta lista?',
    'todos.deleteTask': 'Eliminar Tarea',
    'todos.deleteTaskConfirm': '¿Está seguro de que desea eliminar esta tarea?',
    'todos.task': 'tarea',
    'todos.tasks': 'tareas',
    'todos.create': 'Crear',
    'todos.addTaskBtn': 'Agregar Tarea',
    'todos.error': 'Por favor ingrese un título de tarea',
    'todos.errorList': 'Por favor ingrese un nombre de lista',
    
    // Shopping
    'shopping.title': 'Listas de Compras',
    'shopping.newList': 'Nueva Lista',
    'shopping.noLists': 'Sin Listas de Compras Aún',
    'shopping.createFirst': 'Cree su primera lista para comenzar',
    'shopping.noItems': 'Sin Artículos Aún',
    'shopping.addItem': 'Agregue un artículo para comenzar',
    'shopping.newItem': 'Nuevo Artículo',
    'shopping.itemName': 'Nombre del Artículo',
    'shopping.enterItemName': 'Ingrese el nombre del artículo',
    'shopping.quantity': 'Cantidad (Opcional)',
    'shopping.quantityPlaceholder': 'p.ej., 2 kg, 1 docena',
    'shopping.category': 'Categoría',
    'shopping.listName': 'Nombre de la Lista',
    'shopping.enterListName': 'Ingrese el nombre de la lista',
    'shopping.deleteList': 'Eliminar Lista',
    'shopping.deleteListConfirm': '¿Está seguro de que desea eliminar esta lista?',
    'shopping.deleteItem': 'Eliminar Artículo',
    'shopping.deleteItemConfirm': '¿Está seguro de que desea eliminar este artículo?',
    'shopping.items': 'artículos',
    'shopping.qty': 'Cantidad',
    'shopping.create': 'Crear',
    'shopping.addItem': 'Agregar Artículo',
    'shopping.error': 'Por favor ingrese un nombre de artículo',
    'shopping.errorList': 'Por favor ingrese un nombre de lista',
    
    // Notes
    'notes.title': 'Notas',
    'notes.newNote': 'Nueva Nota',
    'notes.noNotes': 'Sin Notas Aún',
    'notes.createFirst': 'Cree su primera nota para comenzar',
    'notes.noteTitle': 'Título',
    'notes.enterTitle': 'Ingrese el título de la nota',
    'notes.content': 'Contenido',
    'notes.enterContent': 'Ingrese el contenido de la nota',
    'notes.date': 'Fecha (Opcional)',
    'notes.selectDate': 'Seleccionar fecha',
    'notes.time': 'Hora (Opcional)',
    'notes.selectTime': 'Seleccionar hora',
    'notes.deleteNote': 'Eliminar Nota',
    'notes.deleteConfirm': '¿Está seguro de que desea eliminar esta nota?',
    'notes.editNote': 'Editar Nota',
    'notes.update': 'Actualizar',
    'notes.error': 'Por favor ingrese un título y contenido',
    
    // Home
    'home.welcome': 'Bienvenido',
    'home.trackHealth': 'Realice un seguimiento de sus métricas de salud y manténgase informado',
    'home.calendar': 'Calendario',
    'home.calendarDesc': 'Vea sus registros de salud por fecha',
    'home.addEntry': 'Agregar Entrada',
    'home.addEntryDesc': 'Registre pulso, presión arterial y medicamentos',
    'home.samsungHealth': 'Samsung Health',
    'home.samsungHealthDesc': 'Sincronice datos de su Galaxy Watch 7',
    'home.healthInfo': 'Información de Salud',
    'home.healthInfoDesc': 'Aprenda sobre POTS y trastornos circulatorios',
    'home.reminders': 'Recordatorios',
    'home.remindersDesc': 'Establezca recordatorios para mediciones y medicamentos',
    'home.forum': 'Foro',
    'home.forumDesc': 'Conéctese con miembros de la comunidad',
    'home.lastUpdated': 'Última actualización',
  },
  fr: {
    // Onboarding
    'onboarding.welcome': 'Bienvenue sur PulsLog',
    'onboarding.welcome.description': 'Suivez vos métriques de santé et restez informé de votre santé circulatoire.',
    'onboarding.name': 'Quel est votre nom?',
    'onboarding.age': 'Votre Âge',
    'onboarding.age.description': 'Cela nous aide à calculer vos métriques de santé de base.',
    'onboarding.gender': 'Votre Genre',
    'onboarding.gender.description': 'Cela nous aide à fournir des informations de santé personnalisées.',
    'onboarding.measurements': 'Vos Mesures',
    'onboarding.measurements.description': 'La hauteur (cm) et le poids (kg) nous aident à calculer votre ligne de base de santé.',
    'onboarding.language': 'Sélectionnez Votre Langue',
    'onboarding.language.description': 'Choisissez votre langue préférée pour l\'application.',
    'onboarding.next': 'Suivant',
    'onboarding.back': 'Retour',
    'onboarding.getStarted': 'Commencer',
    'onboarding.enterName': 'Entrez votre nom',
    'onboarding.enterAge': 'Entrez votre âge',
    'onboarding.height': 'Hauteur (cm)',
    'onboarding.weight': 'Poids (kg)',
    'onboarding.male': 'Masculin',
    'onboarding.female': 'Féminin',
    'onboarding.other': 'Autre',

    // Profile
    'profile.title': 'Profil',
    'profile.healthProfile': 'Profil de Santé',
    'profile.height': 'Hauteur',
    'profile.weight': 'Poids',
    'profile.avgPulse': 'Pouls Moyen',
    'profile.averagePulseByActivity': 'Pouls Moyen par Niveau d\'Activité',
    'profile.resting': 'Repos',
    'profile.lightActivity': 'Activité Légère',
    'profile.sportsActivity': 'Activité Sportive',
    'profile.healthBaselines': 'Lignes de Base de Santé',
    'profile.systolic': 'Systolique',
    'profile.diastolic': 'Diastolique',
    'profile.about': 'À Propos de PulsLog',
    'profile.aboutDescription': 'PulsLog vous aide à suivre votre pouls, votre tension artérielle et vos données de médicaments. Il est conçu pour les personnes atteintes du POTS et d\'autres troubles circulatoires.',
    'profile.version': 'Version 1.0.0',
    'profile.resetProfile': 'Réinitialiser le Profil',
    'profile.language': 'Langue',
    'profile.editProfile': 'Modifier le Profil',
    'profile.cancel': 'Annuler',
    'profile.save': 'Enregistrer',
    'profile.resetConfirm': 'Réinitialiser le Profil',
    'profile.resetConfirmMessage': 'Êtes-vous sûr de vouloir réinitialiser votre profil? Cela vous ramènera à l\'écran d\'intégration.',

    // Other/Organizer
    'other.title': 'Organisateur',
    'other.description': 'Gérez vos tâches, achats et notes',
    'other.todos': '✓ Listes de Tâches',
    'other.shopping': '🛒 Listes d\'Achats',
    'other.notes': '📝 Notes',
    'other.dataLocal': 'Toutes vos données sont enregistrées localement sur votre appareil',

    // Common
    'common.list': 'liste',
    'common.lists': 'listes',
    'common.note': 'note',
    'common.notes': 'notes',
    
    // Add Entry
    'addEntry.title': 'Ajouter une Entrée de Santé',
    'addEntry.time': 'Heure',
    'addEntry.activityLevel': 'Niveau d\'Activité',
    'addEntry.resting': 'Repos',
    'addEntry.light': 'Activité Légère',
    'addEntry.sports': 'Activité Sportive',
    'addEntry.medication': 'Médicament',
    'addEntry.medicationName': 'Nom du médicament',
    'addEntry.medicationAmount': 'Quantité (p.ex., 1 comprimé, 5ml)',
    'addEntry.pulse': 'Pouls (bpm)',
    'addEntry.pulseResting': 'Repos',
    'addEntry.pulseSitting': 'Assis',
    'addEntry.pulseStanding': 'Debout',
    'addEntry.bloodPressure': 'Tension Artérielle (mmHg)',
    'addEntry.systolic': 'Systolique',
    'addEntry.diastolic': 'Diastolique',
    'addEntry.mood': 'Humeur / Bien-être',
    'addEntry.notes': 'Notes',
    'addEntry.additionalNotes': 'Notes supplémentaires',
    'addEntry.cancel': 'Annuler',
    'addEntry.save': 'Enregistrer l\'Entrée',
    'addEntry.error': 'Veuillez entrer au moins les données de pouls ou de tension artérielle',
    'addEntry.success': 'Entrée enregistrée avec succès',
    
    // Calendar
    'calendar.title': 'Calendrier',
    'calendar.deleteEntry': 'Supprimer l\'Entrée',
    'calendar.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette entrée?',
    'calendar.noEntries': 'Aucune entrée pour',
    'calendar.pulse': 'Pouls',
    'calendar.bp': 'TA',
    'calendar.medication': 'Médicament',
    
    // Reminders
    'reminders.title': 'Rappels',
    'reminders.description': 'Définissez des rappels pour vos mesures et vos médicaments',
    'reminders.pulse': 'Mesures de Pouls',
    'reminders.medicationReminder': 'Médicament',
    'reminders.addPulse': 'Ajouter un Rappel de Pouls',
    'reminders.addMedication': 'Ajouter un Rappel de Médicament',
    'reminders.note': 'Remarque',
    'reminders.noteText': 'Les rappels sont stockés localement sur votre appareil. Activez les notifications dans les paramètres de votre appareil pour recevoir des alertes.',
    
    // Forum
    'forum.title': 'Forum Communautaire',
    'forum.placeholder': 'Partagez vos pensées ou posez une question...',
    'forum.post': 'Publier',
    'forum.recentMessages': 'Messages Récents',
    'forum.noMessages': 'Aucun message pour l\'instant. Soyez le premier à publier!',
    'forum.error': 'Veuillez entrer un message',
    'forum.success': 'Message publié!',
    
    // Todos
    'todos.title': 'Listes de Tâches',
    'todos.newList': 'Nouvelle Liste',
    'todos.noLists': 'Aucune Liste de Tâches Encore',
    'todos.createFirst': 'Créez votre première liste pour commencer',
    'todos.noTasks': 'Aucune Tâche Encore',
    'todos.addTask': 'Ajoutez une tâche pour commencer',
    'todos.newTask': 'Nouvelle Tâche',
    'todos.taskTitle': 'Titre de la Tâche',
    'todos.enterTaskTitle': 'Entrez le titre de la tâche',
    'todos.dueDate': 'Date d\'Échéance (Optionnel)',
    'todos.selectDate': 'Sélectionner la date',
    'todos.dueTime': 'Heure d\'Échéance (Optionnel)',
    'todos.selectTime': 'Sélectionner l\'heure',
    'todos.listName': 'Nom de la Liste',
    'todos.enterListName': 'Entrez le nom de la liste',
    'todos.deleteList': 'Supprimer la Liste',
    'todos.deleteListConfirm': 'Êtes-vous sûr de vouloir supprimer cette liste?',
    'todos.deleteTask': 'Supprimer la Tâche',
    'todos.deleteTaskConfirm': 'Êtes-vous sûr de vouloir supprimer cette tâche?',
    'todos.task': 'tâche',
    'todos.tasks': 'tâches',
    'todos.create': 'Créer',
    'todos.addTaskBtn': 'Ajouter une Tâche',
    'todos.error': 'Veuillez entrer un titre de tâche',
    'todos.errorList': 'Veuillez entrer un nom de liste',
    
    // Shopping
    'shopping.title': 'Listes d\'Achats',
    'shopping.newList': 'Nouvelle Liste',
    'shopping.noLists': 'Aucune Liste d\'Achats Encore',
    'shopping.createFirst': 'Créez votre première liste pour commencer',
    'shopping.noItems': 'Aucun Article Encore',
    'shopping.addItem': 'Ajoutez un article pour commencer',
    'shopping.newItem': 'Nouvel Article',
    'shopping.itemName': 'Nom de l\'Article',
    'shopping.enterItemName': 'Entrez le nom de l\'article',
    'shopping.quantity': 'Quantité (Optionnel)',
    'shopping.quantityPlaceholder': 'p.ex., 2 kg, 1 douzaine',
    'shopping.category': 'Catégorie',
    'shopping.listName': 'Nom de la Liste',
    'shopping.enterListName': 'Entrez le nom de la liste',
    'shopping.deleteList': 'Supprimer la Liste',
    'shopping.deleteListConfirm': 'Êtes-vous sûr de vouloir supprimer cette liste?',
    'shopping.deleteItem': 'Supprimer l\'Article',
    'shopping.deleteItemConfirm': 'Êtes-vous sûr de vouloir supprimer cet article?',
    'shopping.items': 'articles',
    'shopping.qty': 'Quantité',
    'shopping.create': 'Créer',
    'shopping.addItem': 'Ajouter un Article',
    'shopping.error': 'Veuillez entrer un nom d\'article',
    'shopping.errorList': 'Veuillez entrer un nom de liste',
    
    // Notes
    'notes.title': 'Notes',
    'notes.newNote': 'Nouvelle Note',
    'notes.noNotes': 'Aucune Note Encore',
    'notes.createFirst': 'Créez votre première note pour commencer',
    'notes.noteTitle': 'Titre',
    'notes.enterTitle': 'Entrez le titre de la note',
    'notes.content': 'Contenu',
    'notes.enterContent': 'Entrez le contenu de la note',
    'notes.date': 'Date (Optionnel)',
    'notes.selectDate': 'Sélectionner la date',
    'notes.time': 'Heure (Optionnel)',
    'notes.selectTime': 'Sélectionner l\'heure',
    'notes.deleteNote': 'Supprimer la Note',
    'notes.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette note?',
    'notes.editNote': 'Modifier la Note',
    'notes.update': 'Mettre à Jour',
    'notes.error': 'Veuillez entrer un titre et un contenu',
    
    // Home
    'home.welcome': 'Bienvenue',
    'home.trackHealth': 'Suivez vos métriques de santé et restez informé',
    'home.calendar': 'Calendrier',
    'home.calendarDesc': 'Consultez vos dossiers de santé par date',
    'home.addEntry': 'Ajouter une Entrée',
    'home.addEntryDesc': 'Enregistrez le pouls, la tension artérielle et les médicaments',
    'home.samsungHealth': 'Samsung Health',
    'home.samsungHealthDesc': 'Synchronisez les données de votre Galaxy Watch 7',
    'home.healthInfo': 'Informations de Santé',
    'home.healthInfoDesc': 'En savoir plus sur le POTS et les troubles circulatoires',
    'home.reminders': 'Rappels',
    'home.remindersDesc': 'Définissez des rappels pour les mesures et les médicaments',
    'home.forum': 'Forum',
    'home.forumDesc': 'Connectez-vous avec les membres de la communauté',
    'home.lastUpdated': 'Dernière mise à jour',
  },
};

export const getTranslation = (key: string, language: Language = 'en'): string => {
  return translations[language]?.[key] || translations['en']?.[key] || key;
};

export const colors = {
  background: '#F5F5F5',
  text: '#212121',
  textSecondary: '#757575',
  primary: '#2979FF',
  secondary: '#4CAF50',
  accent: '#FFAB40',
  card: '#FFFFFF',
  highlight: '#FFD54F',
  error: '#F44336',
  warning: '#FF9800',
  success: '#4CAF50',
  lightGray: '#E0E0E0',
  darkGray: '#424242',
};

export const buttonStyles = StyleSheet.create({
  instructionsButton: {
    backgroundColor: colors.primary,
    alignSelf: 'center',
    width: '100%',
  },
  backButton: {
    backgroundColor: colors.lightGray,
    alignSelf: 'center',
    width: '100%',
  },
});

export const commonStyles = StyleSheet.create({
  wrapper: {
    backgroundColor: colors.background,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
    width: '100%',
    height: '100%',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: 800,
    width: '100%',
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    color: colors.text,
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    color: colors.text,
    marginBottom: 12,
  },
  text: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text,
    marginBottom: 8,
    lineHeight: 24,
    textAlign: 'center',
  },
  textSecondary: {
    fontSize: 14,
    fontWeight: '400',
    color: colors.textSecondary,
    marginBottom: 8,
    lineHeight: 20,
  },
  section: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginVertical: 12,
  },
  buttonContainer: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginVertical: 8,
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.lightGray,
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    width: '100%',
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.1)',
    elevation: 3,
  },
  input: {
    backgroundColor: colors.card,
    borderColor: colors.lightGray,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: colors.text,
    marginVertical: 8,
  },
  icon: {
    width: 60,
    height: 60,
    tintColor: colors.primary,
  },
});
