import { StyleSheet, ViewStyle, TextStyle } from 'react-native';

export type Language = 'en' | 'de' | 'es' | 'fr';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Onboarding
    'onboarding.welcome': 'Welcome to PulsLog',
    'onboarding.welcome.description': 'Track your health metrics and stay informed about your circulatory health.',
    'onboarding.name': "What's your name?",
    'onboarding.age': 'Your Age',
    'onboarding.age.description': 'This helps us calculate your baseline health metrics.',
    'onboarding.gender': 'Your Gender',
    'onboarding.gender.description': 'This helps us provide personalized health insights.',
    'onboarding.measurements': 'Your Measurements',
    'onboarding.measurements.description': 'Height (cm) and Weight (kg) help us calculate your health baseline.',
    'onboarding.language': 'Select Your Language',
    'onboarding.language.description': 'Choose your preferred language for the app.',
    'onboarding.next': 'Next',
    'onboarding.back': 'Back',
    'onboarding.getStarted': 'Get Started',
    'onboarding.enterName': 'Enter your name',
    'onboarding.enterAge': 'Enter your age',
    'onboarding.height': 'Height (cm)',
    'onboarding.weight': 'Weight (kg)',
    'onboarding.male': 'Male',
    'onboarding.female': 'Female',
    'onboarding.other': 'Other',

    // Profile
    'profile.title': 'Profile',
    'profile.healthProfile': 'Health Profile',
    'profile.height': 'Height',
    'profile.weight': 'Weight',
    'profile.avgPulse': 'Avg. Pulse',
    'profile.averagePulseByActivity': 'Average Pulse by Activity Level',
    'profile.resting': 'Resting',
    'profile.lightActivity': 'Light Activity',
    'profile.sportsActivity': 'Sports Activity',
    'profile.healthBaselines': 'Health Baselines',
    'profile.systolic': 'Systolic',
    'profile.diastolic': 'Diastolic',
    'profile.about': 'About PulsLog',
    'profile.aboutDescription': 'PulsLog helps you track your pulse, blood pressure, and medication data. It\'s designed for people with POTS and other circulatory disorders.',
    'profile.version': 'Version 1.0.0',
    'profile.resetProfile': 'Reset Profile',
    'profile.language': 'Language',
    'profile.editProfile': 'Edit Profile',
    'profile.cancel': 'Cancel',
    'profile.save': 'Save',
    'profile.resetConfirm': 'Reset Profile',
    'profile.resetConfirmMessage': 'Are you sure you want to reset your profile? This will take you back to the onboarding screen.',

    // Other/Organizer
    'other.title': 'Organizer',
    'other.description': 'Manage your tasks, shopping, and notes',
    'other.todos': '✓ To-Do Lists',
    'other.shopping': '🛒 Shopping Lists',
    'other.notes': '📝 Notes',
    'other.dataLocal': 'All your data is saved locally on your device',

    // Common
    'common.list': 'list',
    'common.lists': 'lists',
    'common.note': 'note',
    'common.notes': 'notes',
  },
  de: {
    // Onboarding
    'onboarding.welcome': 'Willkommen bei PulsLog',
    'onboarding.welcome.description': 'Verfolgen Sie Ihre Gesundheitsmetriken und bleiben Sie über Ihre Kreislaufgesundheit informiert.',
    'onboarding.name': 'Wie heißen Sie?',
    'onboarding.age': 'Ihr Alter',
    'onboarding.age.description': 'Dies hilft uns, Ihre Basis-Gesundheitsmetriken zu berechnen.',
    'onboarding.gender': 'Ihr Geschlecht',
    'onboarding.gender.description': 'Dies hilft uns, personalisierte Gesundheitseinblicke zu geben.',
    'onboarding.measurements': 'Ihre Messungen',
    'onboarding.measurements.description': 'Größe (cm) und Gewicht (kg) helfen uns, Ihre Gesundheitsgrundlage zu berechnen.',
    'onboarding.language': 'Wählen Sie Ihre Sprache',
    'onboarding.language.description': 'Wählen Sie Ihre bevorzugte Sprache für die App.',
    'onboarding.next': 'Weiter',
    'onboarding.back': 'Zurück',
    'onboarding.getStarted': 'Loslegen',
    'onboarding.enterName': 'Geben Sie Ihren Namen ein',
    'onboarding.enterAge': 'Geben Sie Ihr Alter ein',
    'onboarding.height': 'Größe (cm)',
    'onboarding.weight': 'Gewicht (kg)',
    'onboarding.male': 'Männlich',
    'onboarding.female': 'Weiblich',
    'onboarding.other': 'Sonstiges',

    // Profile
    'profile.title': 'Profil',
    'profile.healthProfile': 'Gesundheitsprofil',
    'profile.height': 'Größe',
    'profile.weight': 'Gewicht',
    'profile.avgPulse': 'Durchschn. Puls',
    'profile.averagePulseByActivity': 'Durchschnittlicher Puls nach Aktivitätsniveau',
    'profile.resting': 'Ruhe',
    'profile.lightActivity': 'Leichte Aktivität',
    'profile.sportsActivity': 'Sportliche Aktivität',
    'profile.healthBaselines': 'Gesundheitsgrundlagen',
    'profile.systolic': 'Systolisch',
    'profile.diastolic': 'Diastolisch',
    'profile.about': 'Über PulsLog',
    'profile.aboutDescription': 'PulsLog hilft Ihnen, Ihren Puls, Blutdruck und Medikamentendaten zu verfolgen. Es ist für Menschen mit POTS und anderen Kreislaufstörungen konzipiert.',
    'profile.version': 'Version 1.0.0',
    'profile.resetProfile': 'Profil zurücksetzen',
    'profile.language': 'Sprache',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.cancel': 'Abbrechen',
    'profile.save': 'Speichern',
    'profile.resetConfirm': 'Profil zurücksetzen',
    'profile.resetConfirmMessage': 'Sind Sie sicher, dass Sie Ihr Profil zurücksetzen möchten? Dies bringt Sie zurück zum Onboarding-Bildschirm.',

    // Other/Organizer
    'other.title': 'Organizer',
    'other.description': 'Verwalten Sie Ihre Aufgaben, Einkäufe und Notizen',
    'other.todos': '✓ To-Do-Listen',
    'other.shopping': '🛒 Einkaufslisten',
    'other.notes': '📝 Notizen',
    'other.dataLocal': 'Alle Ihre Daten werden lokal auf Ihrem Gerät gespeichert',

    // Common
    'common.list': 'Liste',
    'common.lists': 'Listen',
    'common.note': 'Notiz',
    'common.notes': 'Notizen',
  },
  es: {
    // Onboarding
    'onboarding.welcome': 'Bienvenido a PulsLog',
    'onboarding.welcome.description': 'Realice un seguimiento de sus métricas de salud y manténgase informado sobre su salud circulatoria.',
    'onboarding.name': '¿Cuál es su nombre?',
    'onboarding.age': 'Su Edad',
    'onboarding.age.description': 'Esto nos ayuda a calcular sus métricas de salud de referencia.',
    'onboarding.gender': 'Su Género',
    'onboarding.gender.description': 'Esto nos ayuda a proporcionar información de salud personalizada.',
    'onboarding.measurements': 'Sus Medidas',
    'onboarding.measurements.description': 'La altura (cm) y el peso (kg) nos ayudan a calcular su línea de base de salud.',
    'onboarding.language': 'Seleccione Su Idioma',
    'onboarding.language.description': 'Elija su idioma preferido para la aplicación.',
    'onboarding.next': 'Siguiente',
    'onboarding.back': 'Atrás',
    'onboarding.getStarted': 'Comenzar',
    'onboarding.enterName': 'Ingrese su nombre',
    'onboarding.enterAge': 'Ingrese su edad',
    'onboarding.height': 'Altura (cm)',
    'onboarding.weight': 'Peso (kg)',
    'onboarding.male': 'Masculino',
    'onboarding.female': 'Femenino',
    'onboarding.other': 'Otro',

    // Profile
    'profile.title': 'Perfil',
    'profile.healthProfile': 'Perfil de Salud',
    'profile.height': 'Altura',
    'profile.weight': 'Peso',
    'profile.avgPulse': 'Pulso Promedio',
    'profile.averagePulseByActivity': 'Pulso Promedio por Nivel de Actividad',
    'profile.resting': 'Reposo',
    'profile.lightActivity': 'Actividad Ligera',
    'profile.sportsActivity': 'Actividad Deportiva',
    'profile.healthBaselines': 'Líneas de Base de Salud',
    'profile.systolic': 'Sistólica',
    'profile.diastolic': 'Diastólica',
    'profile.about': 'Acerca de PulsLog',
    'profile.aboutDescription': 'PulsLog le ayuda a realizar un seguimiento de su pulso, presión arterial y datos de medicamentos. Está diseñado para personas con POTS y otros trastornos circulatorios.',
    'profile.version': 'Versión 1.0.0',
    'profile.resetProfile': 'Restablecer Perfil',
    'profile.language': 'Idioma',
    'profile.editProfile': 'Editar Perfil',
    'profile.cancel': 'Cancelar',
    'profile.save': 'Guardar',
    'profile.resetConfirm': 'Restablecer Perfil',
    'profile.resetConfirmMessage': '¿Está seguro de que desea restablecer su perfil? Esto lo llevará de vuelta a la pantalla de incorporación.',

    // Other/Organizer
    'other.title': 'Organizador',
    'other.description': 'Administre sus tareas, compras y notas',
    'other.todos': '✓ Listas de Tareas',
    'other.shopping': '🛒 Listas de Compras',
    'other.notes': '📝 Notas',
    'other.dataLocal': 'Todos sus datos se guardan localmente en su dispositivo',

    // Common
    'common.list': 'lista',
    'common.lists': 'listas',
    'common.note': 'nota',
    'common.notes': 'notas',
  },
  fr: {
    // Onboarding
    'onboarding.welcome': 'Bienvenue sur PulsLog',
    'onboarding.welcome.description': 'Suivez vos métriques de santé et restez informé de votre santé circulatoire.',
    'onboarding.name': 'Quel est votre nom?',
    'onboarding.age': 'Votre Âge',
    'onboarding.age.description': 'Cela nous aide à calculer vos métriques de santé de base.',
    'onboarding.gender': 'Votre Genre',
    'onboarding.gender.description': 'Cela nous aide à fournir des informations de santé personnalisées.',
    'onboarding.measurements': 'Vos Mesures',
    'onboarding.measurements.description': 'La hauteur (cm) et le poids (kg) nous aident à calculer votre ligne de base de santé.',
    'onboarding.language': 'Sélectionnez Votre Langue',
    'onboarding.language.description': 'Choisissez votre langue préférée pour l\'application.',
    'onboarding.next': 'Suivant',
    'onboarding.back': 'Retour',
    'onboarding.getStarted': 'Commencer',
    'onboarding.enterName': 'Entrez votre nom',
    'onboarding.enterAge': 'Entrez votre âge',
    'onboarding.height': 'Hauteur (cm)',
    'onboarding.weight': 'Poids (kg)',
    'onboarding.male': 'Masculin',
    'onboarding.female': 'Féminin',
    'onboarding.other': 'Autre',

    // Profile
    'profile.title': 'Profil',
    'profile.healthProfile': 'Profil de Santé',
    'profile.height': 'Hauteur',
    'profile.weight': 'Poids',
    'profile.avgPulse': 'Pouls Moyen',
    'profile.averagePulseByActivity': 'Pouls Moyen par Niveau d\'Activité',
    'profile.resting': 'Repos',
    'profile.lightActivity': 'Activité Légère',
    'profile.sportsActivity': 'Activité Sportive',
    'profile.healthBaselines': 'Lignes de Base de Santé',
    'profile.systolic': 'Systolique',
    'profile.diastolic': 'Diastolique',
    'profile.about': 'À Propos de PulsLog',
    'profile.aboutDescription': 'PulsLog vous aide à suivre votre pouls, votre tension artérielle et vos données de médicaments. Il est conçu pour les personnes atteintes du POTS et d\'autres troubles circulatoires.',
    'profile.version': 'Version 1.0.0',
    'profile.resetProfile': 'Réinitialiser le Profil',
    'profile.language': 'Langue',
    'profile.editProfile': 'Modifier le Profil',
    'profile.cancel': 'Annuler',
    'profile.save': 'Enregistrer',
    'profile.resetConfirm': 'Réinitialiser le Profil',
    'profile.resetConfirmMessage': 'Êtes-vous sûr de vouloir réinitialiser votre profil? Cela vous ramènera à l\'écran d\'intégration.',

    // Other/Organizer
    'other.title': 'Organisateur',
    'other.description': 'Gérez vos tâches, achats et notes',
    'other.todos': '✓ Listes de Tâches',
    'other.shopping': '🛒 Listes d\'Achats',
    'other.notes': '📝 Notes',
    'other.dataLocal': 'Toutes vos données sont enregistrées localement sur votre appareil',

    // Common
    'common.list': 'liste',
    'common.lists': 'listes',
    'common.note': 'note',
    'common.notes': 'notes',
  },
};

export const getTranslation = (key: string, language: Language = 'en'): string => {
  return translations[language]?.[key] || translations['en']?.[key] || key;
};

export const colors = {
  background: '#F5F5F5',
  text: '#212121',
  textSecondary: '#757575',
  primary: '#2979FF',
  secondary: '#4CAF50',
  accent: '#FFAB40',
  card: '#FFFFFF',
  highlight: '#FFD54F',
  error: '#F44336',
  warning: '#FF9800',
  success: '#4CAF50',
  lightGray: '#E0E0E0',
  darkGray: '#424242',
};

export const buttonStyles = StyleSheet.create({
  instructionsButton: {
    backgroundColor: colors.primary,
    alignSelf: 'center',
    width: '100%',
  },
  backButton: {
    backgroundColor: colors.lightGray,
    alignSelf: 'center',
    width: '100%',
  },
});

export const commonStyles = StyleSheet.create({
  wrapper: {
    backgroundColor: colors.background,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
    width: '100%',
    height: '100%',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: 800,
    width: '100%',
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    color: colors.text,
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    color: colors.text,
    marginBottom: 12,
  },
  text: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text,
    marginBottom: 8,
    lineHeight: 24,
    textAlign: 'center',
  },
  textSecondary: {
    fontSize: 14,
    fontWeight: '400',
    color: colors.textSecondary,
    marginBottom: 8,
    lineHeight: 20,
  },
  section: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginVertical: 12,
  },
  buttonContainer: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginVertical: 8,
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.lightGray,
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    width: '100%',
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.1)',
    elevation: 3,
  },
  input: {
    backgroundColor: colors.card,
    borderColor: colors.lightGray,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: colors.text,
    marginVertical: 8,
  },
  icon: {
    width: 60,
    height: 60,
    tintColor: colors.primary,
  },
});
